---
url: "https://gist.githubusercontent.com/bigsauron/93b70e2e81a2c186389179635ce1b8c6/raw/b38d8e9b6dc3d3af9f166a9c5877b1d1c902ceec/swagger"
dom_id: "#swagger-ui"
validatorUrl: "https://validator.swagger.io/validator"
